sudo: required
services:
  - docker

before_install:
  - docker build -t mchvs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mchvs/react-test npm test

after_success:
  - docker build -t mchvs/multi-client ./client
  - docker build -t mchvs/multi-nginx ./nginx
  - docker build -t mchvs/multi-server ./server
  - docker build -t mchvs/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mchvs/multi-client
  - docker push mchvs/multi-nginx
  - docker push mchvs/multi-server
  - docker push mchvs/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-128549674050
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
